
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"


notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: eDR18lcFiN925PsfFLU4pLxokCJosMNH6gTJ5JvE3KuMJC2r7U0s0IXU7c7mm39gccb6blrHE+F3sn4iwsUX/CNqDdlemYmNJxmMwSiKUR8f3fO2J95LTiE/5lLp2usjODAnLvPBNTJnL3LM60zfU+AFw+qfnscyepvZ33w0utck7DlHFQ0c5CrXdIHaR+QT6T8jxdTxBHwg1vwM/6xnpqe5VIfyl4ZNZx+MXd/a6miJaZzIx2GsHBEJ1JYR0l0hkNraUYnDJjbEYo9kzO7ZUszP/Kw1BpQFg9wWNihOmFcfh6J6Bp440xiGpWQ1lrUdx+0lRDlIEFG6wg2GSzPom2hPgsugnRo1zCVOEZUwvNeQjlm7sgCluvv9kuEcQjic5NFBV1JY1WOSbiGj4XeuPn1b7Zqdke9IgDiCuANa0yc44PeL9x6XY1e/VTHxPeBdbMNOWfutyXBXYRq2YX12CYdc9gwQsuDKcUpOBJzlc+4rBUlwH3P+sJVsUpuqdtr4h28U+GPj0Y0VGdE8mo+8p2zgOoReRH2bfN5SHkMlyrmWgXHCIwesAIujnymiJkZ8ch/2Cy53800FTsiVCiCPh8IKp/PL8UaVoe2A9G0EQDVrE854dhViGjuF1UlJ2on/gc+mKudTEnhehmYzJsOZIkhe8aKTrPKDynKU9LEhe48=

env:
  global:
    - _R_CHECK_TIMINGS_="0"
